### ISSUE TITLE
Tooltip not visible

### ISSUE THREAD

**Issue by NicolasBircksZR** [emilk/egui_plot#30]
**Describe the bug**

When hovering over a Line/Point in the plot we usually see the tooltip with the x and y values but if the line is near to the top of the plotting area the tooltip is not completely shown anymore:
![image](https://github.com/user-attachments/assets/44f7795c-b1c6-4742-a16f-3686674610f5)

**To Reproduce**
1. Go to [https://emilk.github.io/egui_plot](https://emilk.github.io/egui_plot)
2. Move the plot in the plotting area so its near to the top and 
3. Hover over the line

**Expected behavior**
The position of the tooltip should switch to the bottom of the mouse so the tooltip can be shown correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/e487781f-6d1a-40b7-afaa-763afc24f19b)
![image](https://github.com/user-attachments/assets/5fc398f4-bd3c-4ee4-8e28-52eada79f8cf)

**Comment by bircni** [comment]
already fixed!
